#############################################################################
# Makefile for building: ProjetP12
# Generated by qmake (2.01a) (Qt 4.7.4) on: mer. juin 6 16:18:19 2012
# Project:  ProjetP12.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ProjetP12.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mainwindow.cpp \
		main.cpp \
		logsystem.cpp \
		logmessage.cpp \
		fonctions.cpp \
		constante.cpp \
		complexe.cpp \
		rationnel.cpp \
		pile.cpp \
		entier.cpp \
		reel.cpp \
		expression.cpp \
		calculatrice.cpp moc_mainwindow.cpp \
		moc_pile.cpp
OBJECTS       = mainwindow.o \
		main.o \
		logsystem.o \
		logmessage.o \
		fonctions.o \
		constante.o \
		complexe.o \
		rationnel.o \
		pile.o \
		entier.o \
		reel.o \
		expression.o \
		calculatrice.o \
		moc_mainwindow.o \
		moc_pile.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		ProjetP12.pro
QMAKE_TARGET  = ProjetP12
DESTDIR       = 
TARGET        = ProjetP12

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ProjetP12.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ProjetP12.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ProjetP12.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ProjetP121.0.0 || $(MKDIR) .tmp/ProjetP121.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ProjetP121.0.0/ && $(COPY_FILE) --parents mainwindow.h logsystem.h logmessage.h fonctions.h constante.h complexe.h rationnel.h pile.h entier.h reel.h expression.h calculatrice.h .tmp/ProjetP121.0.0/ && $(COPY_FILE) --parents mainwindow.cpp main.cpp logsystem.cpp logmessage.cpp fonctions.cpp constante.cpp complexe.cpp rationnel.cpp pile.cpp entier.cpp reel.cpp expression.cpp calculatrice.cpp .tmp/ProjetP121.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/ProjetP121.0.0/ && (cd `dirname .tmp/ProjetP121.0.0` && $(TAR) ProjetP121.0.0.tar ProjetP121.0.0 && $(COMPRESS) ProjetP121.0.0.tar) && $(MOVE) `dirname .tmp/ProjetP121.0.0`/ProjetP121.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ProjetP121.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_pile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pile.cpp
moc_mainwindow.cpp: pile.h \
		constante.h \
		complexe.h \
		entier.h \
		rationnel.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_pile.cpp: constante.h \
		complexe.h \
		entier.h \
		rationnel.h \
		pile.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) pile.h -o moc_pile.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

mainwindow.o: mainwindow.cpp mainwindow.h \
		pile.h \
		constante.h \
		complexe.h \
		entier.h \
		rationnel.h \
		ui_mainwindow.h \
		fonctions.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

main.o: main.cpp mainwindow.h \
		pile.h \
		constante.h \
		complexe.h \
		entier.h \
		rationnel.h \
		fonctions.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

logsystem.o: logsystem.cpp logsystem.h \
		logmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logsystem.o logsystem.cpp

logmessage.o: logmessage.cpp logmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logmessage.o logmessage.cpp

fonctions.o: fonctions.cpp fonctions.h \
		constante.h \
		complexe.h \
		entier.h \
		rationnel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fonctions.o fonctions.cpp

constante.o: constante.cpp constante.h \
		complexe.h \
		entier.h \
		rationnel.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constante.o constante.cpp

complexe.o: complexe.cpp complexe.h \
		constante.h \
		entier.h \
		rationnel.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o complexe.o complexe.cpp

rationnel.o: rationnel.cpp complexe.h \
		constante.h \
		entier.h \
		rationnel.h \
		reel.h \
		fonctions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rationnel.o rationnel.cpp

pile.o: pile.cpp pile.h \
		constante.h \
		complexe.h \
		entier.h \
		rationnel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pile.o pile.cpp

entier.o: entier.cpp complexe.h \
		constante.h \
		entier.h \
		rationnel.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entier.o entier.cpp

reel.o: reel.cpp complexe.h \
		constante.h \
		entier.h \
		rationnel.h \
		reel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reel.o reel.cpp

expression.o: expression.cpp expression.h \
		constante.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o expression.o expression.cpp

calculatrice.o: calculatrice.cpp calculatrice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calculatrice.o calculatrice.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pile.o: moc_pile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pile.o moc_pile.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

