Complexe
Constante* Complexe::_reelle
Constante* Complexe::_imaginaire
Complexe::Complexe()
Referenced by addition, produit, signe, inv, carre, cube.
Complexe::Complexe(Constante *r, Constante *i)
References important, Constante::recopie.
Complexe::~Complexe()
QString Complexe::afficher() const
References reel_pur, Constante::afficher.
Constante* Complexe::getPartieReelle() const
Referenced by addition, produit, signe, fact, sinus, cosinus, sinush, cosinush, tangente, tangenteh, inv, racine, puissance, logN, log1, Entier::Entier, Rationnel::Rationnel, Reel::Reel.
Constante* Complexe::getPartieImaginaire() const
Referenced by addition, produit, signe, inv, reel_pur.
void Complexe::setReelle(Constante *re)
Referenced by Constante::recopie.
void Complexe::setImaginaire(Constante *im)
Referenced by Constante::recopie.
Complexe::Complexe(Constante *c)
References Constante::recopie.
bool Complexe::reel_pur() const
References getPartieImaginaire, Entier::getValeur, Rationnel::getNumerateur, Reel::getValeur.
Referenced by afficher, fact, sinus, cosinus, sinush, cosinush, tangente, tangenteh, racine, puissance, logN, log1, Entier::Entier, Rationnel::Rationnel, Reel::Reel.
Constante * Complexe::addition(Constante *c)
References Complexe, getPartieReelle, getPartieImaginaire, Constante::addition.
Referenced by produit, soustraction, inv, Entier::addition, Rationnel::addition, Reel::addition.
Constante * Complexe::produit(Constante *c)
References Complexe, getPartieReelle, soustraction, getPartieImaginaire, Constante::produit, addition.
Referenced by division, signe, carre, cube, Entier::produit, Rationnel::produit, Reel::produit.
Constante * Complexe::division(Constante *c)
References produit, inv.
Referenced by inv.
Constante * Complexe::signe()
References Complexe, getPartieReelle, produit, getPartieImaginaire.
Referenced by inv.
Constante * Complexe::soustraction(Constante *c)
References addition, inv.
Referenced by produit.
Constante * Complexe::inv()
References Complexe, getPartieReelle, division, carre, addition, getPartieImaginaire, signe.
Referenced by division, soustraction.
Constante * Complexe::fact()
References reel_pur, getPartieReelle, Constante::fact, moyen.
Constante * Complexe::sinus(bool angle)
References reel_pur, getPartieReelle, Constante::sinus, moyen.
Constante * Complexe::cosinus(bool angle)
References reel_pur, getPartieReelle, Constante::cosinus, moyen.
Constante * Complexe::sinush(bool angle)
References reel_pur, getPartieReelle, Constante::sinush, moyen.
Constante * Complexe::cosinush(bool angle)
References reel_pur, getPartieReelle, Constante::cosinush, moyen.
Constante * Complexe::tangente(bool angle)
References reel_pur, getPartieReelle, Constante::tangente, moyen.
Constante * Complexe::tangenteh(bool angle)
References reel_pur, getPartieReelle, Constante::tangenteh, moyen.
Constante * Complexe::logN()
References reel_pur, getPartieReelle, Constante::logN, moyen.
Constante * Complexe::log1()
References reel_pur, getPartieReelle, Constante::log1, moyen.
Constante * Complexe::puissance(Constante *c)
References reel_pur, getPartieReelle, Constante::puissance, moyen.
Constante * Complexe::carre()
References Complexe, produit.
Referenced by inv.
Constante * Complexe::cube()
References Complexe, produit.
Constante * Complexe::racine()
References reel_pur, getPartieReelle, Constante::racine, moyen.