Reel
double Reel::_valeur
Reel::Reel(double e)
Referenced by addition, produit, signe, inv, sinus, cosinus, cosinush, tangente, tangenteh, sinush, logN, log1, puissance, carre, cube, racine.
Reel::Reel(Constante *c)
References Complexe::reel_pur, Complexe::getPartieReelle, important, getValeur.
virtual Reel::~Reel()
virtual QString Reel::afficher() const
double Reel::getValeur() const
Referenced by Complexe::reel_pur, Entier::addition, Entier::produit, Rationnel::produit, Reel, addition, produit, inv, puissance.
void Reel::setValeur(int v)
Constante * Reel::addition(Constante *c)
References Constante::addition, Complexe::addition, important, Rationnel::addition, Reel, getValeur.
Referenced by soustraction.
Constante * Reel::produit(Constante *c)
References Constante::produit, Rationnel::produit, Reel, getValeur, Complexe::produit, important.
Referenced by division.
Constante * Reel::division(Constante *c)
References produit, Constante::inv.
Constante * Reel::signe()
References Reel.
Constante * Reel::soustraction(Constante *c)
References addition, Constante::signe.
Constante * Reel::inv()
References Reel, getValeur.
Constante * Reel::fact()
References moyen.
Constante * Reel::sinus(bool angle)
References PI, Reel.
Constante * Reel::cosinus(bool angle)
References PI, Reel.
Constante * Reel::sinush(bool angle)
References PI, Reel.
Constante * Reel::cosinush(bool angle)
References PI, Reel.
Constante * Reel::tangente(bool angle)
References PI, Reel.
Constante * Reel::tangenteh(bool angle)
References PI, Reel.
Constante * Reel::logN()
References Reel.
Constante * Reel::log1()
References Reel.
Constante * Reel::puissance(Constante *c)
References getValeur, Reel.
Constante * Reel::carre()
References Reel.
Constante * Reel::cube()
References Reel.
Constante * Reel::racine()
References Reel.