LogSystem
LogSystem * LogSystem::instance
LogSystem & LogSystem::getInstance()
References LogSystem.
Referenced by MainWindow::EVALClicked, Pile::pop, Pile::clear, Pile::dup, Pile::drop, Pile::sauv_pile_context.
void LogSystem::libereInstance()
void LogSystem::ajouterFichierLog(LogMessage m)
References LogMessage::what.
Referenced by ajouterFcihierEtConsole.
void LogSystem::ajouterConsoleLog(LogMessage m)
References LogMessage::what.
Referenced by ajouterFcihierEtConsole.
void LogSystem::ajouterFcihierEtConsole(LogMessage m)
References ajouterConsoleLog, ajouterFichierLog.
Referenced by MainWindow::EVALClicked, Pile::pop, Pile::clear, Pile::dup, Pile::drop, Pile::sauv_pile_context.
LogSystem::LogSystem(const LogSystem &)
LogSystem::LogSystem()
Referenced by getInstance.
void LogSystem::operator=(const LogSystem &)