Entier
int Entier::_valeur
Entier::Entier(int e)
Referenced by addition, produit, signe, fact, sinus, cosinus, sinush, cosinush, tangente, tangenteh, logN, log1, puissance, carre, cube, racine.
Entier::Entier(Constante *c)
References Complexe::reel_pur, Complexe::getPartieReelle, important, Rationnel::getDenominateur, Rationnel::getNumerateur.
virtual Entier::~Entier()
virtual QString Entier::afficher() const
int Entier::getValeur() const
Referenced by Complexe::reel_pur, fact, inv, puissance, Rationnel::Rationnel.
void Entier::setValeur(int v)
Constante * Entier::addition(Constante *c)
References Entier, Complexe::addition, Rationnel::getDenominateur, Rationnel::getNumerateur, Reel::getValeur, important.
Referenced by soustraction, Rationnel::addition.
Constante * Entier::produit(Constante *c)
References Entier, Rationnel::getNumerateur, Rationnel::getDenominateur, Reel::getValeur, Complexe::produit, important.
Referenced by division.
Constante * Entier::signe()
References Entier.
Constante * Entier::division(Constante *c)
References produit, Constante::inv.
Constante * Entier::soustraction(Constante *c)
References addition, Constante::signe.
int Entier::mod(Entier *c)
Constante * Entier::fact()
References getValeur, Entier.
Constante * Entier::inv()
References getValeur.
Constante * Entier::sinus(bool angle)
References PI, Entier.
Constante * Entier::cosinus(bool angle)
References PI, Entier.
Constante * Entier::sinush(bool angle)
References PI, Entier.
Constante * Entier::cosinush(bool angle)
References PI, Entier.
Constante * Entier::tangente(bool angle)
References PI, Entier.
Constante * Entier::tangenteh(bool angle)
References PI, Entier.
Constante * Entier::logN()
References Entier.
Constante * Entier::log1()
References Entier.
Constante * Entier::puissance(Constante *c)
References getValeur, Entier.
Constante * Entier::carre()
References Entier.
Constante * Entier::cube()
References Entier.
Constante * Entier::racine()
References Entier.