Constante
virtual Constante::~Constante()
virtual QString Constante::afficher() const =0
Referenced by Complexe::afficher.
virtual Constante* Constante::addition(Constante *c)
References moyen.
Referenced by Complexe::addition, MainWindow::traiter_bloc_calcul, Pile::sum, Reel::addition.
virtual Constante* Constante::produit(Constante *c)
References moyen.
Referenced by Complexe::produit, MainWindow::traiter_bloc_calcul, Rationnel::produit, Reel::produit.
virtual Constante* Constante::division(Constante *c)
References moyen.
Referenced by MainWindow::traiter_bloc_calcul, Pile::mean.
virtual Constante* Constante::signe()
References moyen.
Referenced by Entier::soustraction, MainWindow::traiter_bloc_calcul, Rationnel::soustraction, Reel::soustraction.
Constante * Constante::recopie()
References recopie, Complexe::setImaginaire, Complexe::setReelle.
Referenced by Complexe::Complexe, recopie, Pile::dup, Pile::copier_pile.
virtual Constante* Constante::soustraction(Constante *c)
References moyen.
Referenced by MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::inv()
References moyen.
Referenced by Entier::division, MainWindow::traiter_bloc_calcul, Rationnel::division, Reel::division.
virtual Constante* Constante::fact()
References moyen.
Referenced by Complexe::fact, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::sinus(bool angle)
References moyen.
Referenced by Complexe::sinus, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::cosinus(bool angle)
References moyen.
Referenced by Complexe::cosinus, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::sinush(bool angle)
References moyen.
Referenced by Complexe::sinush, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::cosinush(bool angle)
References moyen.
Referenced by Complexe::cosinush, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::tangente(bool angle)
References moyen.
Referenced by Complexe::tangente, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::tangenteh(bool angle)
References moyen.
Referenced by Complexe::tangenteh, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::logN()
References moyen.
Referenced by Complexe::logN, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::log1()
References moyen.
Referenced by Complexe::log1, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::puissance(Constante *c)
References moyen.
Referenced by Complexe::puissance, MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::carre()
References moyen.
Referenced by MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::cube()
References moyen.
Referenced by MainWindow::traiter_bloc_calcul.
virtual Constante* Constante::racine()
References moyen.
Referenced by Complexe::racine, MainWindow::traiter_bloc_calcul.