Calculatrice
Calculatrice * Calculatrice::instance
enum MesureAngle Calculatrice::_modAngle
enum Type Calculatrice::_modConstante
bool Calculatrice::_modComplexe
QList<Pile*> Calculatrice::Historique
unsigned int Calculatrice::indice_pile_actuelle
QSettings* Calculatrice::context
Calculatrice::Calculatrice()
Constructeur de la calculatrice.
Construit le QSettings context et restaure la pile enregistré lors de la dernière utilisation.
References stringToConstante, getPileStockage, Pile::push, tracabilite, getInstance.
Referenced by getInstance.
Calculatrice::Calculatrice(const Calculatrice &)
Calculatrice::~Calculatrice()
Dans un Singleton, nécessité d'avoir une instante de type static.
void Calculatrice::operator=(const Calculatrice &)
Calculatrice & Calculatrice::getInstance()
References Calculatrice.
Referenced by Calculatrice, annuler, retablir, MainWindow::MainWindow, MainWindow::vider_pileClicked, MainWindow::supprimer_tete_pileClicked, MainWindow::dupliquer_tete_pileClicked, MainWindow::_modDegresToggled, MainWindow::_modRadiansToggled, MainWindow::_modComplexeONClicked, MainWindow::_modComplexeOFFClicked, MainWindow::_clavierBasicStateChange, MainWindow::_clavierAvanceStateChange, MainWindow::_modReel, MainWindow::_modRationnel, MainWindow::_modEntier, MainWindow::annulerClicked, MainWindow::retablirClicked, MainWindow::ENTERClicked, MainWindow::traiter_bloc_calcul, stringToConstante, MainWindow::traiter_bloc_expression, MainWindow::EVALClicked, MainWindow::dernier_element_expression, MainWindow::closeEvent, Pile::sauv_pile_context, Rationnel::afficher.
void Calculatrice::libereInstance()
void Calculatrice::annuler()
References tracabilite, getInstance.
Referenced by MainWindow::annulerClicked.
void Calculatrice::retablir()
References tracabilite, getInstance.
Referenced by MainWindow::retablirClicked.
Pile* Calculatrice::getPileStockage()
Referenced by Calculatrice, MainWindow::MainWindow, MainWindow::supprimer_tete_pileClicked, MainWindow::dupliquer_tete_pileClicked, MainWindow::ENTERClicked, MainWindow::traiter_bloc_calcul, MainWindow::traiter_bloc_expression, MainWindow::EVALClicked, MainWindow::dernier_element_expression, MainWindow::closeEvent.
int Calculatrice::taille_pile_hitorique()
void Calculatrice::afficher_toutes_piles_hitorique()
void Calculatrice::saisie_nouvelle_pile(Pile *nouvelle)
Referenced by MainWindow::vider_pileClicked, MainWindow::supprimer_tete_pileClicked, MainWindow::dupliquer_tete_pileClicked, MainWindow::ENTERClicked.
enum MesureAngle Calculatrice::getMesureAngle() const
Referenced by MainWindow::traiter_bloc_calcul.
enum Type Calculatrice::getModConstante() const
bool Calculatrice::getModComplexe() const
Referenced by stringToConstante.
QSettings* Calculatrice::getContext()
Referenced by MainWindow::_modDegresToggled, MainWindow::_modRadiansToggled, MainWindow::_modComplexeONClicked, MainWindow::_modComplexeOFFClicked, MainWindow::_clavierBasicStateChange, MainWindow::_clavierAvanceStateChange, MainWindow::_modReel, MainWindow::_modRationnel, MainWindow::_modEntier, Pile::sauv_pile_context.
void Calculatrice::setModConstante(enum Type t)
Referenced by MainWindow::_modReel, MainWindow::_modRationnel, MainWindow::_modEntier.
void Calculatrice::setMesureAngle(enum MesureAngle a)
Referenced by MainWindow::_modDegresToggled, MainWindow::_modRadiansToggled.
void Calculatrice::setModComplexe(bool c)
Referenced by MainWindow::_modComplexeONClicked, MainWindow::_modComplexeOFFClicked.