Pile
QList<Constante*> Pile::p
Constante * Pile::pop()
References tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole.
Referenced by MainWindow::traiter_bloc_calcul, MainWindow::EVALClicked, MainWindow::dernier_element_expression.
Constante* Pile::top()
void Pile::push(Constante *ptr)
Referenced by Calculatrice::Calculatrice, MainWindow::traiter_bloc_calcul, MainWindow::traiter_bloc_expression, MainWindow::EVALClicked, MainWindow::dernier_element_expression.
bool Pile::isEmpty() const
Referenced by MainWindow::traiter_bloc_calcul.
int Pile::size() const
Pile::Pile(QObject *parent=0)
Pile::~Pile()
Constante * Pile::sum(unsigned int x=2)
References Constante::addition.
Constante * Pile::mean(unsigned int x=2)
References Constante::division.
void Pile::clear()
References tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole.
void Pile::dup()
References Constante::recopie, tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole.
Referenced by MainWindow::dupliquer_tete_pileClicked.
void Pile::drop()
References tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole.
Referenced by MainWindow::supprimer_tete_pileClicked.
void Pile::swap(unsigned int x, unsigned int y)
QString Pile::afficher() const
Pile * Pile::copier_pile()
References Constante::recopie.
Referenced by MainWindow::supprimer_tete_pileClicked, MainWindow::dupliquer_tete_pileClicked, MainWindow::ENTERClicked.
void Pile::sauv_pile_context()
References Calculatrice::getInstance, Calculatrice::getContext, tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole.
Referenced by MainWindow::closeEvent.
int Pile::rowCount(const QModelIndex &parent) const
QVariant Pile::data(const QModelIndex &index, int role) const
void Pile::operator=(const Pile &)