MainWindow
Ui::MainWindow* MainWindow::ui
void MainWindow::closeEvent(QCloseEvent *event)
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::sauv_pile_context.
void MainWindow::loadFromFile()
MainWindow::MainWindow(QWidget *parent=0)
References Ui_MainWindow::setupUi, Ui_MainWindow::num0, num0Clicked, Ui_MainWindow::num1, num1Clicked, Ui_MainWindow::num2, num2Clicked, Ui_MainWindow::num3, num3Clicked, Ui_MainWindow::num4, num4Clicked, Ui_MainWindow::num5, num5Clicked, Ui_MainWindow::num6, num6Clicked, Ui_MainWindow::num7, num7Clicked, Ui_MainWindow::num8, num8Clicked, Ui_MainWindow::num9, num9Clicked, Ui_MainWindow::POINT, POINTClicked, Ui_MainWindow::ESPACE, ESPACEClicked, Ui_MainWindow::DOLLAR, DOLLARClicked, Ui_MainWindow::QUOTE, QUOTEClicked, Ui_MainWindow::CE, CEClicked, Ui_MainWindow::C, CClicked, Ui_MainWindow::ENTER, ENTERClicked, Ui_MainWindow::EVAL, EVALClicked, Ui_MainWindow::PIBOUTON, PIBOUTONClicked, Ui_MainWindow::FACTORIEL, FACTORIELClicked, Ui_MainWindow::ADDITIONNER, ADDITIONNERClicked, Ui_MainWindow::SOUSTRAIRE, SOUSTRAIREClicked, Ui_MainWindow::MULTIPLIER, MULTIPLIERClicked, Ui_MainWindow::DIVISER, DIVISERClicked, Ui_MainWindow::POW, POWClicked, Ui_MainWindow::SIN, SINClicked, Ui_MainWindow::COS, COSClicked, Ui_MainWindow::TAN, TANClicked, Ui_MainWindow::SINH, SINHClicked, Ui_MainWindow::COSH, COSHClicked, Ui_MainWindow::TANH, TANHClicked, Ui_MainWindow::MOD, MODClicked, Ui_MainWindow::SIGN, SIGNClicked, Ui_MainWindow::LN, LNClicked, Ui_MainWindow::LOG, LOGClicked, Ui_MainWindow::INV, INVClicked, Ui_MainWindow::SQR, SQRClicked, Ui_MainWindow::SQRT, SQRTClicked, Ui_MainWindow::CUBE, CUBEClicked, Ui_MainWindow::annuler, annulerClicked, Ui_MainWindow::retablir, retablirClicked, Ui_MainWindow::vider_pile, vider_pileClicked, Ui_MainWindow::supprimer_tete_pile, supprimer_tete_pileClicked, Ui_MainWindow::dupliquer_tete_pile, dupliquer_tete_pileClicked, Ui_MainWindow::_clavierBasic, _clavierBasicStateChange, Ui_MainWindow::_clavierAvance, _clavierAvanceStateChange, Ui_MainWindow::_modComplexeOFF, _modComplexeOFFClicked, Ui_MainWindow::_modComplexeON, _modComplexeONClicked, Ui_MainWindow::_modDegres, _modDegresToggled, Ui_MainWindow::_modRadians, _modRadiansToggled, Ui_MainWindow::_modEntiers, _modEntier, Ui_MainWindow::_modRationnels, _modRationnel, Ui_MainWindow::_modReels, _modReel, Calculatrice::getInstance, Calculatrice::getPileStockage, Ui_MainWindow::listView.
bool MainWindow::dernier_element_expression(QString chaine)
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::pop, traiter_bloc_expression, Pile::push.
Referenced by ENTERClicked.
MainWindow::~MainWindow()
void MainWindow::traiter_bloc_expression(QString s)
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::push.
Referenced by ENTERClicked, dernier_element_expression.
void MainWindow::traiter_bloc_calcul(QString s)
References Calculatrice::getInstance, Calculatrice::getMesureAngle, degre, Calculatrice::getPileStockage, Pile::isEmpty, Pile::pop, moyen, Pile::push, Constante::addition, Constante::produit, Constante::division, Constante::soustraction, Constante::fact, Constante::sinus, Constante::sinush, Constante::cosinus, Constante::cosinush, Constante::tangente, Constante::tangenteh, Constante::inv, Constante::signe, Constante::carre, Constante::racine, Constante::cube, Constante::logN, Constante::puissance, Constante::log1, stringToConstante.
Referenced by ENTERClicked.
void MainWindow::POWClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SINClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::COSClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::TANClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SINHClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::COSHClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::TANHClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::MODClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SIGNClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::LNClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::LOGClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::INVClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SQRClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SQRTClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::CUBEClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::QUOTEClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::CClicked()
References Ui_MainWindow::inputLine, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::CEClicked()
References Ui_MainWindow::inputLine, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::DOLLARClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num0Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num1Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num2Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num3Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num4Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num5Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num6Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num7Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num8Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::num9Clicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::PIBOUTONClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::POINTClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::ESPACEClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::FACTORIELClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::ADDITIONNERClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::SOUSTRAIREClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::MULTIPLIERClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::DIVISERClicked()
References Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::_clavierBasicStateChange(int)
References Ui_MainWindow::widget_clavierBasic, Calculatrice::getInstance, Calculatrice::getContext, Ui_MainWindow::inputLine.
Referenced by MainWindow.
void MainWindow::_clavierAvanceStateChange(int)
References Ui_MainWindow::widget_clavierAvance, Calculatrice::getInstance, Calculatrice::getContext.
Referenced by MainWindow.
void MainWindow::_modComplexeONClicked(bool)
References Calculatrice::getInstance, Calculatrice::setModComplexe, Ui_MainWindow::DOLLAR, Calculatrice::getContext, _modComplexeOFFClicked.
Referenced by MainWindow, _modComplexeOFFClicked.
void MainWindow::_modComplexeOFFClicked(bool)
References Calculatrice::getInstance, Calculatrice::setModComplexe, Ui_MainWindow::DOLLAR, Calculatrice::getContext, _modComplexeONClicked.
Referenced by MainWindow, _modComplexeONClicked.
void MainWindow::_modRadiansToggled(bool)
References Calculatrice::getInstance, Calculatrice::setMesureAngle, radian, Calculatrice::getContext, _modDegresToggled.
Referenced by MainWindow, _modDegresToggled.
void MainWindow::_modDegresToggled(bool)
References Calculatrice::getInstance, Calculatrice::setMesureAngle, degre, Calculatrice::getContext, _modRadiansToggled.
Referenced by MainWindow, _modRadiansToggled.
void MainWindow::_modReel(bool)
References Calculatrice::getInstance, Calculatrice::setModConstante, reel, Calculatrice::getContext, Ui_MainWindow::listView, _modRationnel.
Referenced by MainWindow, _modRationnel.
void MainWindow::_modRationnel(bool)
References Calculatrice::getInstance, Calculatrice::setModConstante, rationnel, Calculatrice::getContext, Ui_MainWindow::listView, _modReel.
Referenced by MainWindow, _modReel, _modEntier.
void MainWindow::_modEntier(bool)
References Calculatrice::getInstance, Calculatrice::setModConstante, entier, Calculatrice::getContext, Ui_MainWindow::listView, _modRationnel.
Referenced by MainWindow.
void MainWindow::retablirClicked()
References Calculatrice::getInstance, Calculatrice::retablir, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::annulerClicked()
References Calculatrice::getInstance, Calculatrice::annuler, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::ENTERClicked()
References Ui_MainWindow::inputLine, Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::copier_pile, Calculatrice::saisie_nouvelle_pile, dernier_element_expression, traiter_bloc_expression, traiter_bloc_calcul, important, Ui_MainWindow::listView.
Referenced by MainWindow, EVALClicked.
void MainWindow::EVALClicked()
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::pop, Ui_MainWindow::inputLine, ENTERClicked, tracabilite, LogSystem::getInstance, LogSystem::ajouterFcihierEtConsole, important, Pile::push.
Referenced by MainWindow.
void MainWindow::vider_pileClicked()
References Calculatrice::getInstance, Calculatrice::saisie_nouvelle_pile, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::supprimer_tete_pileClicked()
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::copier_pile, Calculatrice::saisie_nouvelle_pile, Pile::drop, Ui_MainWindow::listView.
Referenced by MainWindow.
void MainWindow::dupliquer_tete_pileClicked()
References Calculatrice::getInstance, Calculatrice::getPileStockage, Pile::copier_pile, Calculatrice::saisie_nouvelle_pile, Pile::dup, Ui_MainWindow::listView.
Referenced by MainWindow.