Rationnel
int Rationnel::_numerateur
int Rationnel::_denominateur
QString Rationnel::afficher() const
References getDenominateur, Calculatrice::getInstance, entier, reel.
float Rationnel::getNumerateur() const
Referenced by Complexe::reel_pur, Entier::Entier, Entier::addition, Entier::produit, Rationnel, addition, produit, inv, puissance.
float Rationnel::getDenominateur() const
Referenced by Entier::Entier, Entier::addition, Entier::produit, Rationnel, afficher, addition, produit, inv.
void Rationnel::setNumerateur(int v)
References simplification.
void Rationnel::setDenominateur(int v)
References simplification, important.
Rationnel::Rationnel(Constante *c)
References Complexe::reel_pur, Complexe::getPartieReelle, important, Entier::getValeur, getNumerateur, getDenominateur, simplification.
Referenced by addition, produit, signe, sinus, cosinus, sinush, cosinush, tangente, tangenteh, inv, logN, log1, puissance, carre, cube, racine.
Rationnel::Rationnel(int num=0, int den=1)
References important, simplification.
void Rationnel::simplification()
References important, pgcd.
Referenced by Rationnel, addition, setNumerateur, setDenominateur.
virtual Rationnel::~Rationnel()
Constante * Rationnel::addition(Constante *c)
References Entier::addition, Complexe::addition, getDenominateur, getNumerateur, Rationnel, simplification, important.
Referenced by soustraction, Reel::addition.
Constante * Rationnel::produit(Constante *c)
References Constante::produit, Rationnel, getNumerateur, getDenominateur, Reel::getValeur, Complexe::produit, important.
Referenced by division, Reel::produit.
Constante * Rationnel::division(Constante *c)
References produit, Constante::inv.
Constante * Rationnel::signe()
References Rationnel.
Constante * Rationnel::soustraction(Constante *c)
References addition, Constante::signe.
Constante * Rationnel::inv()
References Rationnel, getDenominateur, getNumerateur.
Constante * Rationnel::fact()
References moyen.
Constante * Rationnel::sinus(bool angle)
References PI, Rationnel.
Constante * Rationnel::cosinus(bool angle)
References PI, Rationnel.
Constante * Rationnel::sinush(bool angle)
References PI, Rationnel.
Constante * Rationnel::cosinush(bool angle)
References PI, Rationnel.
Constante * Rationnel::tangente(bool angle)
References PI, Rationnel.
Constante * Rationnel::tangenteh(bool angle)
References PI, Rationnel.
Constante * Rationnel::logN()
References Rationnel.
Constante * Rationnel::log1()
References Rationnel.
Constante * Rationnel::puissance(Constante *c)
References getNumerateur, Rationnel.
Constante * Rationnel::carre()
References Rationnel.
Constante * Rationnel::cube()
References Rationnel.
Constante * Rationnel::racine()
References Rationnel.