mainwindow.h
PI
MesureAngle
Constante* stringToConstante(QString s, bool essayer_construire_complexe)
References Calculatrice::getInstance, Calculatrice::getModComplexe, stringToConstante, moyen.
Referenced by Calculatrice::Calculatrice, MainWindow::traiter_bloc_calcul, stringToConstante.