.TH "Calculatrice" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Calculatrice \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCalculatrice\fP & \fBgetInstance\fP ()"
.br
.ti -1c
.RI "static void \fBlibereInstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBCalculatrice\fP (const \fBCalculatrice\fP &)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBCalculatrice\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
