.TH "/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/calculatrice.h" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/calculatrice.h \- 
.PP
\fBCalculatrice\fP en polonais inversé\&. Singleton de la calculatrice\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'pile\&.h'\fP
.br
\fC#include 'constante\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCalculatrice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCalculatrice\fP en polonais inversé\&. Singleton de la calculatrice\&. 

\fBAuthor:\fP
.RS 4
Aurélien DUMAINE 
.PP
Simon LANCELOT 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
juin 2012
.RE
.PP
Licence : GNU/GPL version 3 (http://www.gnu.org/copyleft/gpl.html) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
