.TH "Complexe" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Complexe \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConstante\fP\&.
.PP
Inherited by \fBFrabriqueComplexe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComplexe\fP (\fBConstante\fP *r, \fBConstante\fP *i)"
.br
.ti -1c
.RI "virtual QString \fBafficher\fP () const "
.br
.ti -1c
.RI "\fBConstante\fP * \fBgetPartieReelle\fP () const "
.br
.ti -1c
.RI "\fBConstante\fP * \fBgetPartieImaginaire\fP () const "
.br
.ti -1c
.RI "void \fBsetReelle\fP (\fBConstante\fP *re)"
.br
.ti -1c
.RI "void \fBsetImaginaire\fP (\fBConstante\fP *im)"
.br
.ti -1c
.RI "\fBComplexe\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBaddition\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBproduit\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBdivision\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsigne\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsoustraction\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBinv\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBfact\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsinus\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
