.TH "/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/constante.h" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/constante.h \- 
.PP
\fBCalculatrice\fP en polonais inversé\&. Classe de la GUI QT-MainWindow\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QtGui>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstante\fP"
.br
.ti -1c
.RI "class \fBFrabriqueConstante\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBentier\fP, \fBrationnel\fP, \fBreel\fP, \fBcomplexe\fP, \fBexpression\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCalculatrice\fP en polonais inversé\&. Classe de la GUI QT-MainWindow\&. 

\fBAuthor:\fP
.RS 4
Aurélien DUMAINE 
.PP
Simon LANCELOT 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
juin 2012
.RE
.PP
Licence : GNU/GPL version 3 (http://www.gnu.org/copyleft/gpl.html) Dépot Git : http://code.google.com/p/lo21-npi/ 
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
