.TH "/home/yuntux/UTC/GI02/LO21/projet/projet_propre/constante.h" 3 "Samedi Juin 16 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/yuntux/UTC/GI02/LO21/projet/projet_propre/constante.h \- 
.PP
\fBCalculatrice\fP en polonais inversé\&. Classe composite de gestion des constantes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include 'logmessage\&.h'\fP
.br
\fC#include 'logsystem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConstante\fP"
.br
.in -1c
.SS "Énumérations"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBentier\fP, \fBrationnel\fP, \fBreel\fP, \fBcomplexe\fP, \fBexpression\fP }"
.br
.in -1c
.SH "Description détaillée"
.PP 
\fBCalculatrice\fP en polonais inversé\&. Classe composite de gestion des constantes\&. 

\fBCalculatrice\fP en polonais inversé\&. Classe de la GUI QT-MainWindow\&.
.PP
\fBAuteur:\fP
.RS 4
Aurélien DUMAINE 
.PP
Simon LANCELOT 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
juin 2012
.RE
.PP
Licence : GNU/GPL version 3 (http://www.gnu.org/copyleft/gpl.html) Dépot Git : http://code.google.com/p/lo21-npi/ 
.PP
Définition dans le fichier \fBconstante\&.h\fP\&.
.SH "Documentation du type de l'énumération"
.PP 
.SS "enum \fBType\fP"
.PP
\fBValeurs énumérées: \fP
.in +1c
.TP
\fB\fIentier \fP\fP
.TP
\fB\fIrationnel \fP\fP
.TP
\fB\fIreel \fP\fP
.TP
\fB\fIcomplexe \fP\fP
.TP
\fB\fIexpression \fP\fP

.PP
Définition à la ligne 22 du fichier constante\&.h\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Calculatrice polonais inversé LO21 à partir du code source\&.
