.TH "Constante" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Constante \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBComplexe\fP, \fBEntier\fP, \fBExpression\fP, \fBRationnel\fP, and \fBReel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual QString \fBafficher\fP () const =0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBaddition\fP (\fBConstante\fP *c)=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBproduit\fP (\fBConstante\fP *c)=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBdivision\fP (\fBConstante\fP *c)=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsigne\fP ()=0"
.br
.ti -1c
.RI "\fBConstante\fP * \fBrecopie\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsoustraction\fP (\fBConstante\fP *c)=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBinv\fP ()=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBfact\fP ()=0"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsinus\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
