.TH "/home/yuntux/UTC/GI02/LO21/projet/projet_propre/entier.h" 3 "Samedi Juin 16 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/yuntux/UTC/GI02/LO21/projet/projet_propre/entier.h \- 
.PP
\fBCalculatrice\fP en polonais inversé\&. Classe \fBEntier\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'constante\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEntier\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
\fBCalculatrice\fP en polonais inversé\&. Classe \fBEntier\fP\&. 

\fBAuteur:\fP
.RS 4
Aurélien DUMAINE 
.PP
Simon LANCELOT 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
juin 2012
.RE
.PP
Licence : GNU/GPL version 3 (http://www.gnu.org/copyleft/gpl.html) Dépot Git : http://code.google.com/p/lo21-npi/ 
.PP
Définition dans le fichier \fBentier\&.h\fP\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Calculatrice polonais inversé LO21 à partir du code source\&.
