.TH "Expression" 3 "Samedi Juin 16 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expression \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <expression\&.h>\fP
.PP
Est dérivée de \fBConstante\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBExpression\fP (QString s)"
.br
.ti -1c
.RI "virtual \fB~Expression\fP ()"
.br
.ti -1c
.RI "QString \fBgetExpr\fP () const "
.br
.ti -1c
.RI "void \fBsetExpr\fP (QString e)"
.br
.ti -1c
.RI "virtual QString \fBafficher\fP () const "
.br
.in -1c
.SH "Description détaillée"
.PP 
Définition à la ligne 7 du fichier expression\&.h\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "\fBExpression::Expression\fP (QStrings)\fC [inline]\fP"
.PP
Définition à la ligne 11 du fichier expression\&.h\&.
.SS "virtual \fBExpression::~Expression\fP ()\fC [inline, virtual]\fP"
.PP
Définition à la ligne 12 du fichier expression\&.h\&.
.SH "Documentation des fonctions membres"
.PP 
.SS "virtual QString \fBExpression::afficher\fP () const\fC [inline, virtual]\fP"
.PP
Implémente \fBConstante\fP\&.
.PP
Définition à la ligne 15 du fichier expression\&.h\&.
.SS "QString \fBExpression::getExpr\fP () const\fC [inline]\fP"
.PP
Définition à la ligne 13 du fichier expression\&.h\&.
.SS "void \fBExpression::setExpr\fP (QStringe)\fC [inline]\fP"
.PP
Définition à la ligne 14 du fichier expression\&.h\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Calculatrice polonais inversé LO21 à partir du code source\&.
