.TH "/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/fonctions.h" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/yuntux/UTC/GI02/LO21/projet/lo21-npi.2/fonctions.h \- 
.PP
\fBCalculatrice\fP en polonais inversé\&. Fonctions outils diverses\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QStack>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'constante\&.h'\fP
.br
\fC#include 'complexe\&.h'\fP
.br
\fC#include 'rationnel\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpgcd\fP (int a, int b)"
.br
.ti -1c
.RI "int \fBppcm\fP (int X, int Y)"
.br
.ti -1c
.RI "float \fBsinus\fP (\fBRationnel\fP *r)"
.br
.ti -1c
.RI "float \fBcosinus\fP (\fBRationnel\fP *r)"
.br
.ti -1c
.RI "float \fBtangente\fP (\fBRationnel\fP *r)"
.br
.ti -1c
.RI "float \fBsinush\fP (\fBRationnel\fP *r)"
.br
.ti -1c
.RI "float \fBcosinush\fP (\fBRationnel\fP *r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCalculatrice\fP en polonais inversé\&. Fonctions outils diverses\&. 

\fBAuthor:\fP
.RS 4
Aurélien DUMAINE 
.PP
Simon LANCELOT 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
juin 2012
.RE
.PP
Licence : GNU/GPL version 3 (http://www.gnu.org/copyleft/gpl.html) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
