.TH "FrabriqueComplexe" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrabriqueComplexe \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComplexe\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComplexe\fP \fBfabriquer\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
