.TH "Pile" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstante\fP * \fBpop\fP ()"
.br
.ti -1c
.RI "\fBConstante\fP * \fBtop\fP ()"
.br
.ti -1c
.RI "void \fBpush\fP (\fBConstante\fP *ptr)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "\fBPile\fP (QObject *parent=0)"
.br
.ti -1c
.RI "\fBConstante\fP * \fBsum\fP (unsigned int x=2)"
.br
.ti -1c
.RI "QString \fBafficher\fP () const "
.br
.ti -1c
.RI "int \fBrowCount\fP (const QModelIndex &parent) const "
.br
.ti -1c
.RI "QVariant \fBdata\fP (const QModelIndex &index, int role) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator=\fP (const \fBPile\fP &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
