.TH "Reel" 3 "Thu Jun 7 2012" "Calculatrice polonais inversé LO21" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Reel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConstante\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReel\fP (double e)"
.br
.RI "\fIReel(float e):_valeur(e){}\&. \fP"
.ti -1c
.RI "\fBReel\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual QString \fBafficher\fP () const "
.br
.ti -1c
.RI "double \fBgetValeur\fP () const "
.br
.ti -1c
.RI "void \fBsetValeur\fP (int v)"
.br
.ti -1c
.RI "\fBRationnel\fP \fBtoRationnel\fP () const "
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBaddition\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBproduit\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBdivision\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsigne\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsoustraction\fP (\fBConstante\fP *c)"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBinv\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBfact\fP ()"
.br
.ti -1c
.RI "virtual \fBConstante\fP * \fBsinus\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Calculatrice polonais inversé LO21 from the source code\&.
